//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace websocket_chat_application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locations_Data
    {
        public int PK_LOC_ID { get; set; }
        public int locId { get; set; }
        public string country { get; set; }
        public string region { get; set; }
        public string city { get; set; }
        public string postalCode { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string metroCode { get; set; }
    }
}
