//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace websocket_chat_application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Location
    {
        public int PK_MASTERID { get; set; }
        public string Start_IPv4_address { get; set; }
        public string End_IPv4_address { get; set; }
        public long startIpNum { get; set; }
        public long endIpNum { get; set; }
        public int locId { get; set; }
    }
}
