//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace websocket_chat_application
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniqueNumbers_Test
    {
        public int PK_uid_test { get; set; }
        public string uniqueid { get; set; }
    }
}
